# Generated by Django 3.2 on 2021-04-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='salary',
            field=models.IntegerField(default=1),
        ),
    ]
