# Generated by Django 3.2 on 2021-04-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobs_addman'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
