# Generated by Django 3.2 on 2021-04-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='job/'),
        ),
    ]
